# Generated by Django 4.0.6 on 2022-08-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recicle',
            name='typeclothings',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
