# Generated by Django 4.0.6 on 2022-08-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recicle', '0002_recicle_typeclothings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recicle',
            name='ilustration',
            field=models.ImageField(null=True, upload_to='picture/', verbose_name='ilustration'),
        ),
    ]
