# Generated by Django 4.0.6 on 2022-07-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('number_course', models.IntegerField()),
                ('teacher', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ilustration', models.ImageField(null=True, upload_to='picture/', verbose_name='ilustration')),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
