# Generated by Django 4.0.6 on 2022-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewingcourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalizedfabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_desing', models.CharField(max_length=100)),
                ('type_fabric', models.CharField(max_length=100)),
                ('fabric_roll', models.IntegerField()),
                ('size_roll', models.IntegerField()),
                ('characterictics', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ilustration', models.ImageField(null=True, upload_to='picture/', verbose_name='ilustration')),
                ('discount', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
