# Generated by Django 4.0.6 on 2022-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('genres', models.CharField(max_length=255, verbose_name='genres')),
                ('editorial', models.CharField(max_length=255)),
                ('picture', models.ImageField(null=True, upload_to='picture/', verbose_name='picture')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
    ]
