# Generated by Django 4.0.6 on 2022-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librerias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='picture',
        ),
        migrations.AddField(
            model_name='libro',
            name='ilustration',
            field=models.ImageField(null=True, upload_to='picture/', verbose_name='ilustration'),
        ),
    ]
